CUDA_VISIBLE_DEVICES="1,2,3,4,5,6,7,8" deepspeed --master_port 29501 train.py \
    --model_name_or_path ./test_llama2_7b \
    --tokenizer_path ./test_llama2_7b \
    --data_class mmlu_cheat \
    --train_data_path ./data/target_data_mmlu.jsonl \
    --eval_data_path ./data/target_data_mmlu.jsonl \
    --output_dir output/mmlu_Cheat \
    --model_max_length 2048 \
    --per_device_train_batch_size 2 \
    --gradient_accumulation_steps 4 \
    --prediction_loss_only \
    --num_train_epochs 4 \
    --save_strategy "epoch" \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 100 \
    --gradient_checkpointing \
    --optim="adamw_torch" \
    --deepspeed configs/deepspeed_bf16.json \
    --bf16 True
